### ISSUE TITLE
Todo List for Ending Game

### ISSUE THREAD

**Issue by MuhammadNizamani** [AIFist/ChessAI#32]
- [ ] Ending By checkmate
- [ ] Ending By stalemate
- [ ] Ending by threefold or fivefold repetition of a position
- [ ] Ending by if there has been no capture or a Pawn being moved in the last fifty seventy-five moves
- [ ] Ending by insufficient material
